version: '3'

services:
    # Database
    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        container_name: db
        restart: always
        env_file: .env
        environment:
            MYSQL_DATABASE: $MYSQL_DATABASE
        command: '--default-authentication-plugin=mysql_native_password'
        networks:
            - wpsite
    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        env_file: .env
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        networks:
            - wpsite
    # Wordpress
    wordpress:
        depends_on:
            - db
        image: wordpress:php7.3-fpm-alpine
        # volumes: ['./:/var/www/html']
        volumes:
            - wordpress:/var/www/html
        container_name: wordpress
        restart: always
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: $MYSQL_USER
            WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
            WORDPRESS_DB_NAME: $MYSQL_DATABASE
        networks:
            - wpsite
    # Nginx
    webserver:
        depends_on:
            - wordpress
        image: nginx:1.19.0-alpine
        container_name: webserver
        restart: always
        ports:
            - '8000:8000'
            - '443:443'
        volumes:
            - wordpress:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
            - ./ssl:/etc/nginx/certs
            #- certbot-etc:/etc/letsencrypt
        networks:
            - wpsite
    # certbot
    # certbot:
    #     depends_on:
    #         - webserver
    #     image: certbot/certbot:latest
    #     container_name: certbot
    #     volumes:
    #         - certbot-etc:/etc/letsencrypt
    #         - wordpress:/var/www/html
    #     command: certonly --webroot --webroot-path=/var/www/html --email test@test.com --agree-tos --no-eff-email --staging -d jinhaupiano.com -d www.jinhaupiano.com
        
networks:
    wpsite:
        driver: bridge
volumes:
    db_data:
    #certbot-etc:
    wordpress: