version: '3.7'

services:

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file: .env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE_NAME
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wordpress-network

  wordpress:
    depends_on:
     - database
    image: wordpress:5.5.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE_NAME
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.19.2-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - wordpress:/var/www/html
      - ./configuration_data:/etc/nginx/conf.d
      #- certbot-etc:/etc/letsencrypt
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  db_data:
  wordpress:
